apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - minio-secrets.yaml
  - secrets.yaml
  - objectstore.yaml
  - database.yaml
  - scheduled-backup.yaml
  - storage-config.yaml
  - storage-data.yaml
  - deployment.yaml
  - configmap.yaml
  - service-http.yaml
  - service-ssh.yaml
